Bugfix swe 1881 translations provider spinner
senseteq-io/dent-in-patient pull request #13
Opened 2022-08-03 13:34 UTC by sashka2131

2022-08-03 13:37 UTC, GingerBoy14 requested changes

2022-08-03 13:37 UTC, GingerBoy14 commented on src/contexts/Translation/TranslationsProvider.js
> +
move to separate file

2022-08-04 08:29 UTC, Arthur-Pochinok-MENTA approved these changes

2022-08-04 08:29 UTC, Arthur-Pochinok-MENTA commented on src/domains/User/context/UserProvider.js
> +      getDocument(COLLECTIONS.USERS, user.uid).then((doc) => {
Where is the .catch section?
What will be if there is an error during getDocument operation for whatever reason?

2022-08-04 09:10 UTC, GingerBoy14 approved these changes

2022-08-04 09:11 UTC, merged