Bugfix swe 643 fix vipps multiple calling
senseteq-io/dent-in-patient pull request #4
Opened 2022-07-08 23:08 UTC by sashka2131

2022-07-11 08:33 UTC, alexpassss commented on src/hooks/useVippsLogin.js
> +          await fetch(PROD_API_URL + '/vipps/authorize', {
Create universal function for such requests

2022-07-11 08:33 UTC, alexpassss commented on src/hooks/useVippsLogin.js
> +          description: 'Can not login user!',
Where is translations?

2022-07-11 08:34 UTC, VladBogach commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const { user, loading, artificialLoading } = useUser() // uncomment this part if you need to add extra conditions based on data from the DB
remove comment, explain what is artificial loading

2022-07-11 08:36 UTC, VladBogach commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const isLoadingCombined = useMemo(
bad name, better can be computedLoading, mergedLoading, combinedLoading

2022-07-11 08:38 UTC, VladBogach commented on src/hooks/useTransformRoutesRedirectProperties.js
> +      !isUnauthenticatedPath &&
!isLoggedIn && ...

2022-07-11 08:39 UTC, VladBogach commented on src/hooks/useTransformRoutesRedirectProperties.js
> +      (authLoading || loading) && location.pathname !== VIPPS_LOGIN_CALLBACK,
I think, there are must be check on isLoadingCombined property

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA requested changes

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/domains/Session/hooks/useVippsAuth/useVippsAuth.js
> +        notification.error({
it's better to throw an error in this place, so u will have same error handling flow for all places/checks etc in catch section only (reduces amount of code u have to write).

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/domains/Session/hooks/useVippsFlowBackgroundActions/useVippsFlowBackgroundActions.js
> +      const _userAuthInfo = await vippsLogin(urlParamsObject)
What convention for variable naming did u use here?
Please, remove "_"

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +const PASSWORD_AUTH_PROVIDER = 'password'
Please, move this variable to the global const variables

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const combinedLoading = useMemo(
Absolutely unnecessary to use useMemo here, there are no difficult computations at all...

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const usersNextBookingExist = useMemo(
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const isLoggedIn = useMemo(() => userAuth && user?._id, [userAuth, user])
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const isLoggedOut = useMemo(
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/hooks/useTransformRoutesRedirectProperties.js
> +  const isSpinVisible = useMemo(
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/pages/Auth/VippsCallback.js
>      () =>
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/pages/Auth/VippsCallback.js
>    const pageSubtitle = useMemo(
Same as previous

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/utils/sendBackendRequest.js
> +const PROD_API_URL = process.env.REACT_APP_PROD_API_URL
Bad naming, imagine if app used 3 or 4 different API-s, which API_URL would be this one of API №1 or №2?
The naming is not semantic, but should be

2022-07-11 12:26 UTC, Arthur-Pochinok-MENTA commented on src/utils/sendBackendRequest.js
> +const PROD_API_URL = process.env.REACT_APP_PROD_API_URL
Or change function + file names into more semantic...
Because it's not clear to which backend we are gonna send our request

2022-07-11 16:00 UTC, VladBogach commented on src/domains/Session/helpers/transformUserDataFromVipps.js
> +    bookingId: isAuth ? null : state,
bad property naming state (which contains id)

2022-07-11 16:01 UTC, VladBogach commented on src/domains/Session/hooks/useVippsAuth/useVippsAuth.js
> +          data: error.message
Not translated text will be present in app

2022-07-11 16:02 UTC, VladBogach commented on src/domains/Session/hooks/useVippsFlowBackgroundActions/useVippsFlowBackgroundActions.js
> +    const processVippsLogin = async () => {
is better to move fucntion inside if else structure to prevent recreation

2022-07-11 16:02 UTC, VladBogach commented on src/domains/Session/hooks/useVippsFlowBackgroundActions/useVippsFlowBackgroundActions.js
> +          description: `Failed to update booking. ${e.message}`
text without translation

2022-07-11 16:03 UTC, VladBogach commented on src/utils/sendBackendRequest.js
> +      description: `${errorDescription}. ${error.message}`,
text without translation

2022-07-12 10:40 UTC, sashka2131 commented on src/domains/Session/helpers/transformUserDataFromVipps.js
> +    bookingId: isAuth ? null : state,
state is vipps property, for booking I pass bookingId to this property, for auth userId, so its better to leave as vipps property state or maybe rename as computedId

2022-07-13 10:10 UTC, GingerBoy14 requested changes

2022-07-13 10:10 UTC, GingerBoy14 commented on src/domains/Booking/components/BookingSimpleView/BookingSimpleView.js
> +          'Booking can not be canceled less than 48 hours before the start time'
missed translation

2022-07-13 10:10 UTC, GingerBoy14 commented on src/domains/Session/hooks/useVippsAuth/useVippsAuth.js
> +        history.push('/auth')
use route path from constants

2022-07-13 11:10 UTC, GingerBoy14 approved these changes

2022-07-13 12:28 UTC, VladBogach approved these changes

2022-07-13 13:15 UTC, merged