Bugfix swe 1226 set new password page displaying
senseteq-io/dent-in-patient pull request #7
Opened 2022-07-20 12:27 UTC by sashka2131

2022-07-20 13:41 UTC, Arthur-Pochinok-MENTA requested changes

2022-07-20 13:41 UTC, Arthur-Pochinok-MENTA commented on src/components/BoilerplateLayout/BoilerplateLayout.js
> +                left={isVippsCallbackPage ? null : <Back />}
Please, move this computed property outside of the JSX-template (senseteq-coding-standards, rules 5+8 together)

2022-07-20 13:41 UTC, Arthur-Pochinok-MENTA commented on src/domains/Session/components/LoginForm/LoginForm.js
> +    const result = await login({ credentials, onError })
senseteq-coding-standards, RULE 16

2022-07-21 14:24 UTC, sashka2131 commented on src/domains/Session/components/LoginForm/LoginForm.js
> +    const result = await login({ credentials, onError })
Login function code already wrapped into try catch inside

2022-07-21 14:25 UTC, VladBogach approved these changes

2022-07-21 14:29 UTC, Arthur-Pochinok-MENTA approved these changes

2022-07-22 08:07 UTC, merged